description: Provides the ability to create or edit a plugin configuration.
$type: div
children:
  $type: HeaderPage
  props:
    title:
      $map: '`${params.name} Settings`'
  children:
    - $type: Panel
      props:
        inset: true
      children:
        $type: Provider
        props:
          provide:
            data:
              url:
                $map: >-
                  params.id?`/api/kong/apis/${params.name}/plugins/${params.id}`:''
            schema:
              url:
                $map: '`/api/kong/plugins/schema/${params.pluginName}`'
          props:
            dataRoot: config
            successUrl:
              $map: '`/kong/api/${params.name}/plugins`'
            submitTo:
              method:
                $map: 'params.id?"PUT":"POST"'
              url:
                $map: '`/api/kong/apis/${params.name}/plugins`'
            mapper:
              $mapper:
                name: params.pluginName
                config: props
          Component:
            $component: KongForm
paths:
  - '/kong/api/:name/plugin/:pluginName/:id'
  - '/kong/api/:name/plugin/:pluginName'
