description: Provides the ability to create or edit a plugin configuration.
$type: DataEditPage
props:
  title:
    $map: '`${params.apiName} - ${params.pluginName} Settings`'
  source:
    data:
      url:
        $map: params.id?`/api/kong/plugins/${params.id}`:''
    schema:
      url:
        $map: '`/api/kong/plugins/schema/${params.pluginName}`'
  successUrl:
    $map: |
      `/kong/api/${params.apiName}/plugins`
  submitTo:
    method:
      $map: 'params.id?"PUT":"POST"'
    url: /api/kong/plugins
  dataRoot: config
  __mapper:
    $mapper: |
      (()=>{
        console.log(props);
        return props;
        return {
          data: props.data,
          schema: props.schema,
          successUrl: props.successUrl,
          submitTo: props.submitTo
        };
      })();
  Editor:
    $component: KongForm
paths:
  - '/kong/api/:apiName/plugin/:pluginName/:id'
  - '/kong/api/:apiName/plugin/:pluginName'
