description: Provides the ability to edit the settings for a configured API.
$type: DataEditPage
props:
  title:
    $map: '`${params.name} Settings`'
  url:
    $map: |
      params.name?`${config.host || "/api/kong/"}/apis/${params.name}`:''
  schema:
    fields:
      name:
        type: string
        default: ''
        required: true
      hosts:
        type: array
      uris:
        type: array
      methods:
        type: array
      upstream_url:
        type: string
        default: ''
        required: true
      https_only:
        type: boolean
        default: false
      strip_uri:
        type: boolean
        default: false
      retries:
        type: number
        default: 5
        required: true
      http_if_terminated:
        type: boolean
        default: true
      preserve_host:
        type: boolean
        default: false
      upstream_connect_timeout:
        type: number
        default: 60000
        required: true
      upstream_send_timeout:
        type: number
        default: 60000
        required: true
      upstream_read_timeout:
        type: number
        default: 60000
        required: true
  successUrl:
    $mapper: config.env?`/kong/${config.env}/apis`:`/kong/apis`
  submitTo:
    method:
      $map: 'params.name?"PUT":"POST"'
    url:
      $map: |
        `${config.host || '/api/kong'}/apis`
  Editor:
    $component: KongForm
paths:
  - '/kong/api/:name'
  - /kong/api
  - '/kong/:env/api/:name'
  - /kong/:env/api
